version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: doordash_postgres
    environment:
      POSTGRES_USER: Client
      POSTGRES_PASSWORD: DoorDahPassword
      POSTGRES_DB: DoorDashDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "Client", "-d", "DoorDashDb"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  migrations:
    build:
      context: .  # The directory with the Dockerfile
      dockerfile: Dockerfile  # Your existing Dockerfile
    container_name: my_migrations
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["/app/entrypoint.sh"]
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=DoorDashDb;Username=Client;Password=DoorDahPassword"
    volumes:
      - .:/app
    working_dir: /app
  
  api:
    depends_on:
      - postgres
      - migrations 
    build:
      context: . # The directory containing the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5074:5074"            # Map container port 80 to host port 5074
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://0.0.0.0:5074"
      
volumes:
  postgres_data:
