name: Build and Test Application with Docker Compose

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' # Ensure you're using the correct version

      - name: Install Docker Compose
        run: sudo apt-get install docker-compose

      - name: Build and run the application with docker-compose
        run: docker-compose -f DoorDash/docker-compose.yml up -d --build

      - name: Wait for services to be healthy
        run: |
          until docker-compose exec db pg_isready -U Client; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done

      - name: Run migrations
        run: docker-compose exec app dotnet ef database update

      - name: Run tests
        run: docker-compose exec app dotnet test

      - name: Build Docker image
        run: docker-compose build

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.actor }}/doordash-api:${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
